@baseUrl = http://localhost:3003/api

### Login to get Token
# Copy the "token" string from the response and paste it into the 
# @authToken variable in requests/blogs.rest
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "root",
    "password": "secretpassword"
}